#!/bin/bash

#set -x

PATCH_AF_CAN_NAME=socketcan-core-af_can.diff
PATCH_AF_CAN_FILES="$PATCH_AF_CAN_FILES net/can/af_can.c "

PATCH_VERSION_NAME=socketcan-core-version.diff
PATCH_VERSION_FILES="${PATCH_VERSION_FILES} include/linux/can/version.h "

PATCH_DEVICES_NAME=socketcan-core-devices.diff
PATCH_DEVICES_FILES="${PATCH_DEVICES_FILES}/include/linux/can/dev.h "
PATCH_DEVICES_FILES="${PATCH_DEVICES_FILES}/net/can/dev.c "

PATCH_IOCTL_NAME=socketcan-core-ioctl.diff
PATCH_IOCTL_FILES="${PATCH__FILES}/include/linux/can/ioctl.h "

PATCH_PROC_NAME=socketcan-core-proc.diff
PATCH_PROC_FILES="${PATCH__FILES}/net/can/proc.c "

PATCH_RAW_NAME=socketcan-core-raw.diff
PATCH_RAW_FILES="${PATCH_RAW_FILES}/net/can/raw.c "

PATCH_SYSFS_NAME=socketcan-core-sysfs.diff
PATCH_SYSFS_FILES="${PATCH_SYSFS_FILES}/net/can/sysfs.c "
PATCH_SYSFS_FILES="${PATCH_SYSFS_FILES}/net/can/sysfs.h "

PATCH_CANMAKE_NAME=socketcan-core-make.diff
PATCH_CANMAKE_FILES="${PATCH__FILES}/drivers/net/can/Makefile "

PATCH_CANKCONFIG_NAME=socketcan-core-kconfig.diff
PATCH_CANKCONFIG_FILES="${PATCH_CANKCONFIG_FILES}/drivers/net/can/Kconfig "

#PATCH_NETMAKE_NAME=socketcan-net-make.diff
#PATCH_NETMAKE_FILES="${PATCH_NETMAKE_FILES}/drivers/net/Makefile "

PATCH_DRIVER_CCAN_NAME=socketcan-driver-ccan.diff
PATCH_DRIVER_CCAN_FILES="${PATCH_DRIVER_CCAN_FILES}/drivers/net/can/ccan/ccan.c "
PATCH_DRIVER_CCAN_FILES="${PATCH_DRIVER_CCAN_FILES}/drivers/net/can/ccan/ccan.h "
PATCH_DRIVER_CCAN_FILES="${PATCH_DRIVER_CCAN_FILES}/drivers/net/can/ccan/h7202_can.c "

PATCH_DRIVER_MSCAN_NAME=socketcan-driver-mscan.diff
PATCH_DRIVER_MSCAN_FILES="${PATCH_DRIVER_MSCAN_FILES}/drivers/net/can/mscan/Makefile "
PATCH_DRIVER_MSCAN_FILES="${PATCH_DRIVER_MSCAN_FILES}/drivers/net/can/mscan/mpc52xx_can.c "
PATCH_DRIVER_MSCAN_FILES="${PATCH_DRIVER_MSCAN_FILES}/drivers/net/can/mscan/mscan.c "
PATCH_DRIVER_MSCAN_FILES="${PATCH_DRIVER_MSCAN_FILES}/drivers/net/can/mscan/mscan.h "

PATCH_DRIVER_SJA1000_NAME=socketcan-driver-sja1000.diff
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/Makefile "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/ems_pci.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/ixxat_pci.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/kvaser_pci.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/pcm027.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/peak_pci.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/sja1000.c "
PATCH_DRIVER_SJA1000_FILES="${PATCH_DRIVER_SJA1000_FILES}/drivers/net/can/sja1000/sja1000.h "

PATCH_DRIVER_SLCAN_NAME=socketcan-driver-slcan.diff
PATCH_DRIVER_SLCAN_FILES="${PATCH_DRIVER_SLCAN_FILES}/drivers/net/can/slcan.c "

PATCH_DRIVER_VCAN_NAME=socketcan-driver-vcan.diff
PATCH_DRIVER_VCAN_FILES="${PATCH_DRIVER_VCAN_FILES}/drivers/net/can/vcan.c "

PATCH_OLD_NAME=
PATCH_OLD_FILES="${PATCH_OLD_FILES}/vers/net/can/old/hal/c200.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/esdio.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/gw2.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/hal.h "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/io.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/iomem.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/iomux.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/hal/pc7io.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/i82527/i82527.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/i82527/i82527.h "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/i82527/Makefile "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/i82527/proc.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/sja1000/Makefile "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/sja1000/proc.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/sja1000/sja1000.c "
PATCH_OLD_FILES="${PATCH_OLD_FILES}/drivers/net/can/old/sja1000/sja1000.h "

PATCH_BCM_NAME=socketcan-bcm.diff
PATCH_BCM_FILES="${PATCH_BCM_FILES}/net/can/bcm.c "

usage() {
	echo "usage: $0 <path-to-kernel>" >&2
	exit 1
}


#
# main
#

HERE=$(pwd)

[ ! -e $1/MAINTAINERS ] && usage
KERNEL_DIR=$1

if [ -e "${HERE}/socketcan-patches" ]; then
	echo "error: socketcan-patches does already exist, exiting" >&2
	exit 1
fi

# determine kernel version
KERNEL_MAJOR=$(grep "^VERSION =" ${KERNEL_DIR}/Makefile | sed -e "s/[ \t]//g" | sed -e "s/VERSION=//g")
KERNEL_MINOR=$(grep "^PATCHLEVEL =" ${KERNEL_DIR}/Makefile | sed -e "s/[ \t]//g" | sed -e "s/PATCHLEVEL=//g")
KERNEL_MICRO=$(grep "^SUBLEVEL =" ${KERNEL_DIR}/Makefile | sed -e "s/[ \t]//g" | sed -e "s/SUBLEVEL=//g")
KERNEL_EXTRA=$(grep "^EXTRAVERSION =" ${KERNEL_DIR}/Makefile | sed -e "s/[ \t]//g" | sed -e "s/EXTRAVERSION=//g")

mkdir -p "${HERE}/socketcan-patches"
export QUILT_PATCHES=${HERE}/socketcan-patches

echo "creating patches against kernel in $KERNEL_DIR"

num=0


for patch in \
	AF_CAN \
	VERSION \
	DEVICES \
	IOCTL \
	PROC \
	RAW \
	SYSFS \
	CANMAKE \
	CANCONFIG \
	DRIVER_CCAN \
	DRIVER_MSCAN \
	DRIVER_SJA1000 \
	DRIVER_SLCAN \
	DRIVER_VCAN \
	OLD \
	BCM
#	NETMAKE
do
	name=PATCH_${patch}_NAME
	files=PATCH_${patch}_FILES

	num=$((num + 1))

	[ -z "${!name}" ] && continue

	patch_name=$(printf "%02i" $num)-${!name}

	cd ${KERNEL_DIR}
	quilt new ${patch_name} > /dev/null

	for file in ${!files}; do
		quilt add ${file} > /dev/null
		mkdir -p $(dirname ${KERNEL_DIR}/${file})
		${HERE}/strip-src \
			-v ${KERNEL_MAJOR}.${KERNEL_MINOR}.${KERNEL_MICRO}${KERNEL_EXTRA} \
			-i \
			${HERE}/${file} > ${KERNEL_DIR}/${file}
	done

	quilt refresh --diffstat > /dev/null

	if [ -e ${HERE}/socketcan-headers/${!name} ]; then
		cat \
			${HERE}/socketcan-headers/${!name} \
			${HERE}/socketcan-patches/${patch_name} > \
			${HERE}/socketcan-patches/tmp
		mv \
			${HERE}/socketcan-patches/tmp \
			${HERE}/socketcan-patches/${patch_name}
	fi
done

quilt pop -a > /dev/null

#
# check patches
#

for patch in $HERE/socketcan-patches/*.diff; do
	${KERNEL_DIR}/scripts/checkpatch.pl ${patch} > ${patch}.log
done

